version: '2.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch_add
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=123456
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data:rw
    ports:
      - 9244:9200
    restart: unless-stopped
    mem_limit: 4g
  
volumes:
  elasticsearch-data:
    driver: local